baseURL = "https://anuragjain75-gif.github.io/thelilamaya/"
languageCode = "en-us"
title = "The Lilamaya"

[params]
tagline = "Essays on the extraordinary hidden within ordinary life"
author = "Anurag Jain"
