
from pathlib import Path
PROJECT_ROOT=Path(__file__).resolve().parent.parent
FONT_DIR=PROJECT_ROOT/'assets'/'fonts'
LOGO_PATH=PROJECT_ROOT/'static'/'images'/'tree-logo.png'
WIDTH=1200
HEIGHT=630
BACKGROUND='#F8F5EF'
TEXT='#2B2B2B'
MUTED='#555555'
OLIVE='#6F7552'
REGULAR_FONT=FONT_DIR/'CormorantGaramond-Regular.ttf'
ITALIC_FONT=FONT_DIR/'CormorantGaramond-Italic.ttf'
BOLD_FONT=FONT_DIR/'CormorantGaramond-Bold.ttf'
FRAGMENT_BODY_START=64
FRAGMENT_BODY_MIN=48
SIGNATURE_SIZE=36
TITLE_START=50
TITLE_MIN=36
TITLE_BOX_WIDTH=860
TITLE_BOX_HEIGHT=120
DESCRIPTION_SIZE=30
IMAGE_HEIGHT_RATIO=0.65
SIDE_MARGIN=90
TITLE_TOP_MARGIN=24
TITLE_SIGNATURE_GAP=28
MAX_TEXT_WIDTH=860
BOTTOM_MARGIN=30